#!  /bin/sh
# ruby /Users/revence/Documents/Hacks/muse-ic/museic.rb 8888 /Users/revence/Desktop/Misc/Muze/playlist.m3u /Users/revence/Desktop/Misc/Luganda/playlist.m3u /Users/revence/Desktop/Misc/Muze/much-music.m3u
ruby /Users/revence/Documents/Hacks/muse-ic/museic.rb 8888 /Users/revence/Desktop/Misc/Muze/playlist.m3u /Users/revence/Desktop/Misc/Luganda/playlist.m3u /Users/revence/Desktop/Misc/Muze/much-music.m3u
